identifier: dao
name: Daos
type: keyboard
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
  - kscan
  - nvs
  - can
